version: '3.8'

services:
  marketplace:
    build: ./
    command: ./wait-for-postgres.sh db ./marketplace
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=123456
  
  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432